### ISSUE TITLE
(Request) Host latest experimental build.

### ISSUE THREAD

**Issue by Xeddius** [Wolfvak/arm9linuxfw-old#1]
It would be nice to host the latest experimental build so others can get to work debugging and helping to contribute. (For those who either can't or will not compile the code themselves.)

**Comment by ParzivalWolfram** [comment]
I'm running the show for Linux 3DS at this point, and this is just a companion program for that.

It'd probably be up to me to do that.

**Comment by Wolfvak** [comment]
Sorry, I didn't notice this issue was open until today. I suppose it's possible to upload the latest builds somewhere, but I'm not gonna put them out as releases (not even pre-releases), nor in the repo itself.

**Comment by Xeddius** [comment]
An "alpha" build with a "use at your own risk" warning would likely suffice. Could host it with GoogleDrive or Mega.

**Comment by Wolfvak** [comment]
Yeah, GDrive sounds like a good idea.
I'll implement this idea on the next commit and close this issue when it happens.

**Comment by Wolfvak** [comment]
Alright, created a folder for releasing stuff.

Don't know if I'll upload every single one of them, maybe I'll do a weekly thing, or every major release.

https://drive.google.com/open?id=1Mbpn8rb8ToFzyAAdtm3Q9nEdpIEh9nmf
